name: _robots_from_jupyter

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://conda.anaconda.org/conda-forge

dependencies:
  - black
  - conda >=4.6,<4.7
  - conda-build >=3.18.2,<3.19
  - conda-verify
  - constructor >=2.3,<2.4
  - flake8
  - geckodriver
  - python >=3.6,<3.7
  - python-chromedriver-binary ==2.46
  - robotframework
  - robotframework-lint
  - robotframework-seleniumlibrary
